### ISSUE TITLE
Cannot use object of type stdClass as array in

### ISSUE THREAD

**Issue by harveydobson** [webdock-io/php-whmcs#1]
When I try to Regenerate Config options

![image](https://user-images.githubusercontent.com/8660605/167188574-43bb7e54-37a3-4e41-8706-c15930ae9e78.png)

I get the following 500 errors:

![image](https://user-images.githubusercontent.com/8660605/167188704-ab8a33ce-76a8-4466-a9a9-8cf80e7a8e57.png)

![image](https://user-images.githubusercontent.com/8660605/167188367-947e1190-ef28-499c-ac39-c49a9e12ff78.png)

**Comment by webdock-io-admin** [comment]
Resolved in https://github.com/webdock-io/php-whmcs/pull/2 and merged to master
